# 第 3 章：矩陣與矩陣運算

本 Notebook 是 `ch03_matrices.md` 的精簡對照版，涵蓋：矩陣定義與形狀、加法與純量乘法、矩陣乘法（含手算範例驗證）、矩陣乘法不滿足交換律、轉置、特殊矩陣、跡 (trace)。

In [1]:
import numpy as np

## 1. 矩陣的定義與形狀 (shape)

矩陣是 $m \times n$ 的數字陣列，$m$ 為列數、$n$ 為行數。例如：

$$A = \begin{bmatrix} 1 & 2 & 3 \\ 4 & 5 & 6 \end{bmatrix}$$

是一個 $2\times 3$ 矩陣。

In [2]:
A_demo = np.array([[1, 2, 3],
                    [4, 5, 6]])
print("A_demo =\n", A_demo)
print("形狀 (shape):", A_demo.shape, " (2 列 x 3 行)")
print("a_12 =", A_demo[0, 1], "  a_23 =", A_demo[1, 2])

A_demo =
 [[1 2 3]
 [4 5 6]]
形狀 (shape): (2, 3)  (2 列 x 3 行)
a_12 = 2   a_23 = 6


## 2. 矩陣加法與純量乘法

形狀相同才能相加，做法是對應元素相加；純量乘法則對每個元素作用。

$$\begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix} + \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix} = \begin{bmatrix} 6 & 8 \\ 10 & 12 \end{bmatrix}$$

In [3]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

print("M1 + M2 =\n", M1 + M2)
print("2 * M1 =\n", 2 * M1)

M1 + M2 =
 [[ 6  8]
 [10 12]]
2 * M1 =
 [[2 4]
 [6 8]]


## 3. 矩陣乘法

**維度規則**：$A_{m\times n} B_{n\times p} = C_{m\times p}$，內側維度須相符。$c_{ij}$ 是 $A$ 第 $i$ 列與 $B$ 第 $j$ 行的內積。

### 手算範例

$$A = \begin{bmatrix} 1 & 2 \\ 3 & 4 \end{bmatrix}, \quad B = \begin{bmatrix} 5 & 6 \\ 7 & 8 \end{bmatrix}$$

- $c_{11} = (1)(5)+(2)(7) = 19$
- $c_{12} = (1)(6)+(2)(8) = 22$
- $c_{21} = (3)(5)+(4)(7) = 43$
- $c_{22} = (3)(6)+(4)(8) = 50$

$$AB = \begin{bmatrix} 19 & 22 \\ 43 & 50 \end{bmatrix}$$

下方分別用 `@` 運算子與 `np.matmul` 驗證。

In [4]:
A = np.array([[1, 2], [3, 4]])
B = np.array([[5, 6], [7, 8]])

AB_at = A @ B
AB_matmul = np.matmul(A, B)

print("A @ B =\n", AB_at)
print("np.matmul(A, B) =\n", AB_matmul)

expected_AB = np.array([[19, 22], [43, 50]])
print("與手算結果一致:", np.array_equal(AB_at, expected_AB))

A @ B =
 [[19 22]
 [43 50]]
np.matmul(A, B) =
 [[19 22]
 [43 50]]
與手算結果一致: True


## 3.1 矩陣乘法不滿足交換律

再算一次 $BA$，並與 $AB$ 比較。

In [5]:
BA = B @ A
print("B @ A =\n", BA)

expected_BA = np.array([[23, 34], [31, 46]])
print("與手算結果一致:", np.array_equal(BA, expected_BA))
print("AB == BA ?", np.array_equal(AB_at, BA), " -> 矩陣乘法一般不滿足交換律")

B @ A =
 [[23 34]
 [31 46]]
與手算結果一致: True
AB == BA ? False  -> 矩陣乘法一般不滿足交換律


## 4. 轉置矩陣

轉置 $A^T$ 把列與行互換：$(A^T)_{ij} = A_{ji}$。並驗證 $(AB)^T = B^T A^T$。

In [6]:
A_wide = np.array([[1, 2, 3], [4, 5, 6]])
print("A_wide =\n", A_wide)
print("A_wide.T =\n", A_wide.T)

lhs = (A @ B).T
rhs = B.T @ A.T
print("\n(AB)^T =\n", lhs)
print("B^T A^T =\n", rhs)
print("兩者相等:", np.array_equal(lhs, rhs))

A_wide =
 [[1 2 3]
 [4 5 6]]
A_wide.T =
 [[1 4]
 [2 5]
 [3 6]]

(AB)^T =
 [[19 43]
 [22 50]]
B^T A^T =
 [[19 43]
 [22 50]]
兩者相等: True


## 5. 特殊矩陣

零矩陣、單位矩陣 $I$、對角矩陣、對稱矩陣、上/下三角矩陣。

In [7]:
print("零矩陣 (2x3):\n", np.zeros((2, 3)))

I3 = np.eye(3)
print("\n單位矩陣 I3:\n", I3)

D = np.diag([2, 5, -1])
print("\n對角矩陣 D:\n", D)

S = np.array([[1, 2], [2, 3]])
print("\n對稱矩陣 S:\n", S, "\nS 是否對稱 (S == S.T)?", np.array_equal(S, S.T))

A3 = np.array([[1, 2, 3], [0, 1, 4], [5, 6, 0]])
print("\n上三角部分 np.triu(A3):\n", np.triu(A3))
print("\n下三角部分 np.tril(A3):\n", np.tril(A3))

零矩陣 (2x3):
 [[0. 0. 0.]
 [0. 0. 0.]]

單位矩陣 I3:
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]

對角矩陣 D:
 [[ 2  0  0]
 [ 0  5  0]
 [ 0  0 -1]]

對稱矩陣 S:
 [[1 2]
 [2 3]] 
S 是否對稱 (S == S.T)? True

上三角部分 np.triu(A3):
 [[1 2 3]
 [0 1 4]
 [0 0 0]]

下三角部分 np.tril(A3):
 [[1 0 0]
 [0 1 0]
 [5 6 0]]


## 6. 跡 (trace)

$\mathrm{trace}(A) = \sum_i a_{ii}$，滿足線性，且 $\mathrm{trace}(AB) = \mathrm{trace}(BA)$。

In [8]:
print("trace(A) =", np.trace(A), " (預期 1+4=5)")

trace_AB = np.trace(A @ B)
trace_BA = np.trace(B @ A)
print("trace(AB) =", trace_AB, " (預期 69)")
print("trace(BA) =", trace_BA, " (預期 69)")
print("trace(AB) == trace(BA) ?", trace_AB == trace_BA,
      " -> 即使 AB != BA，兩者的跡仍相等")

trace(A) = 5  (預期 1+4=5)
trace(AB) = 69  (預期 69)
trace(BA) = 69  (預期 69)
trace(AB) == trace(BA) ? True  -> 即使 AB != BA，兩者的跡仍相等


## 小結

- 矩陣是 $m\times n$ 的數字陣列；加法/純量乘法逐元素運算。
- 矩陣乘法需內側維度相符，且 **一般不滿足交換律**（$AB \neq BA$）。
- 轉置：$(AB)^T = B^T A^T$。
- 特殊矩陣：零矩陣、單位矩陣、對角矩陣、對稱矩陣、上/下三角矩陣。
- 跡具線性，且 $\mathrm{trace}(AB) = \mathrm{trace}(BA)$。

完整說明請見 [`ch03_matrices.md`](ch03_matrices.md)。