# 第 7 章：向量空間、基底與秩

本 Notebook 是 `ch07_vector_spaces.md` 教學文件的精簡互動版，程式碼與 `ch07_vector_spaces.py` 邏輯一致。

## 學習目標

- 理解向量空間公理的直觀意義（封閉性）
- 判斷一個集合是否為子空間 (subspace)
- 求出矩陣的零空間 (null space) 與行空間 (column space)
- 理解基底 (basis) 與維度 (dimension)
- 驗證秩-零度定理 (Rank-Nullity Theorem)：rank(A) + nullity(A) = n


In [1]:
import numpy as np
from scipy.linalg import null_space

def print_section(title: str) -> None:
    print("\n" + "=" * 60)
    print(title)
    print("=" * 60)


## 1. 向量空間公理的直觀說明

**向量空間**是一個集合 $V$，裡面的向量可以做「加法」與「純量乘法」，且運算結果仍然留在 $V$ 裡面（封閉性）：

- **加法封閉**：$\mathbf{u}, \mathbf{v} \in V \Rightarrow \mathbf{u} + \mathbf{v} \in V$
- **純量乘法封閉**：$\mathbf{u} \in V,\ c \in \mathbb{R} \Rightarrow c\mathbf{u} \in V$

其餘公理（交換律、結合律、有零向量、有反向量、分配律等）在 $\mathbb{R}^n$ 中都自動成立，本章重點放在 $\mathbb{R}^n$ 的子空間上。


In [2]:
u = np.array([1.0, 2.0])
v = np.array([3.0, -1.0])
c = 2.5
print(f"u = {u}, v = {v}, 純量 c = {c}")
print(f"u + v = {u + v}  (仍是 R^2 中的向量 -> 加法封閉)")
print(f"c * u = {c * u}  (仍是 R^2 中的向量 -> 純量乘法封閉)")


u = [1. 2.], v = [ 3. -1.], 純量 c = 2.5
u + v = [4. 1.]  (仍是 R^2 中的向量 -> 加法封閉)
c * u = [2.5 5. ]  (仍是 R^2 中的向量 -> 純量乘法封閉)


## 2. 子空間 (Subspace) 的判斷

判斷 $W$ 是否為 $\mathbb{R}^n$ 的子空間，檢查三個條件：

1. 零向量在 $W$ 中
2. 加法封閉
3. 純量乘法封閉

**任何不通過原點的集合，一定不是子空間。**

- $W = \{(x,y) : y=2x\}$（過原點的直線）**是**子空間。
- $W' = \{(x,y) : y=2x+1\}$（不過原點的直線）**不是**子空間。


In [3]:
print("範例 A：W = {(x,y): y=2x}（通過原點）")
p1 = np.array([1.0, 2.0])
p2 = np.array([-3.0, -6.0])
s = p1 + p2
print(f"  p1={p1}, p2={p2}, p1+p2={s} -> y/x={s[1]/s[0]:.1f}，仍滿足 y=2x，封閉成立")

print("\n範例 B：W' = {(x,y): y=2x+1}（不過原點）")
q1 = np.array([0.0, 1.0])
q2 = np.array([1.0, 3.0])
s2 = q1 + q2
print(f"  q1={q1}, q2={q2}, q1+q2={s2} -> 檢查 y=2x+1 ? {s2[1]} vs {2*s2[0]+1} -> 不相等，封閉性失敗")
print("  結論：不過原點的集合不可能是子空間。")


範例 A：W = {(x,y): y=2x}（通過原點）
  p1=[1. 2.], p2=[-3. -6.], p1+p2=[-2. -4.] -> y/x=2.0，仍滿足 y=2x，封閉成立

範例 B：W' = {(x,y): y=2x+1}（不過原點）
  q1=[0. 1.], q2=[1. 3.], q1+q2=[1. 4.] -> 檢查 y=2x+1 ? 4.0 vs 3.0 -> 不相等，封閉性失敗
  結論：不過原點的集合不可能是子空間。


## 3. 零空間與行空間的定義

- **零空間 (Null Space)**：$\text{Null}(A) = \{\mathbf{x} : A\mathbf{x} = \mathbf{0}\}$，描述被 $A$ 壓縮成原點的方向。
- **行空間 (Column Space)**：$\text{Col}(A) = \text{span}\{$ $A$ 的欄向量 $\}$；$A\mathbf{x}=\mathbf{b}$ 有解 $\iff \mathbf{b} \in \text{Col}(A)$。
- **基底/維度**：線性獨立且能生成整個空間的向量集合稱為基底；基底向量個數稱為維度。
- **秩-零度定理**：$\text{rank}(A) + \text{nullity}(A) = n$（$n$ 為欄數）。

## 手算範例

$$
A = \begin{bmatrix} 1 & 2 & 0 & 3 \\ 0 & 0 & 1 & 2 \\ 1 & 2 & 1 & 5 \end{bmatrix}
$$

高斯消去：$R_3 \leftarrow R_3-R_1$，再 $R_3 \leftarrow R_3-R_2$，得到 RREF：

$$
\begin{bmatrix} 1 & 2 & 0 & 3 \\ 0 & 0 & 1 & 2 \\ 0 & 0 & 0 & 0 \end{bmatrix}
$$

主元在第 1、3 欄 -> $\text{rank}(A)=2$。設自由變數 $x_2=s, x_4=t$：$x_1=-2s-3t$，$x_3=-2t$，

零空間基底 $= \{(-2,1,0,0)^T, (-3,0,-2,1)^T\}$，nullity $=2$。

行空間基底（取原矩陣第 1、3 欄）$= \{(1,0,1)^T, (0,1,1)^T\}$。

驗證：$\text{rank}(A)+\text{nullity}(A) = 2+2 = 4 = n$。


In [4]:
def rref_with_pivots(A: np.ndarray, tol: float = 1e-10):
    """手刻高斯-喬登消去法，回傳 (RREF 矩陣, 主元欄位索引列表)。"""
    M = A.astype(float).copy()
    n_rows, n_cols = M.shape
    pivot_row = 0
    pivot_cols = []
    for col in range(n_cols):
        if pivot_row >= n_rows:
            break
        max_row = pivot_row + np.argmax(np.abs(M[pivot_row:, col]))
        if np.abs(M[max_row, col]) < tol:
            continue
        M[[pivot_row, max_row]] = M[[max_row, pivot_row]]
        M[pivot_row, :] = M[pivot_row, :] / M[pivot_row, col]
        for r in range(n_rows):
            if r != pivot_row:
                M[r, :] -= M[r, col] * M[pivot_row, :]
        pivot_cols.append(col)
        pivot_row += 1
    return M, pivot_cols


def analyze_matrix(A: np.ndarray, name: str) -> None:
    """對矩陣 A 做完整分析：秩、零空間基底、行空間基底，並驗證秩-零度定理。"""
    m, n = A.shape
    print(f"矩陣 {name} ({m} x {n}):")
    print(A)

    rank_A = np.linalg.matrix_rank(A)
    print(f"\nrank({name}) = {rank_A}")

    rref_A, pivot_cols = rref_with_pivots(A)
    print(f"\n{name} 的 RREF:")
    print(np.round(rref_A, 4))
    print(f"主元欄位 (0-indexed): {pivot_cols}")

    col_space_basis = A[:, pivot_cols]
    print(f"\n行空間基底（取原矩陣主元欄）:")
    for i, c in enumerate(pivot_cols):
        print(f"  基底向量 {i+1} = {name} 的第 {c+1} 欄 = {A[:, c]}")

    ns = null_space(A)
    nullity = ns.shape[1]
    print(f"\n零空間基底 (scipy.linalg.null_space):")
    if nullity == 0:
        print("  只有零向量，nullity = 0")
    else:
        for i in range(nullity):
            print(f"  基底向量 {i+1} = {ns[:, i]}")
    print(f"nullity({name}) = {nullity}")

    if nullity > 0:
        residual = A @ ns
        print(f"驗證 {name} @ (零空間基底) 最大絕對誤差 = {np.max(np.abs(residual)):.2e}")

    print(f"\n秩-零度定理: {rank_A} + {nullity} = {rank_A + nullity}，欄數 n = {n}")
    assert rank_A + nullity == n
    print(f"驗證通過！rank({name}) + nullity({name}) = n = {n}")


In [5]:
print_section("矩陣 A：手算範例驗證")
A = np.array([
    [1, 2, 0, 3],
    [0, 0, 1, 2],
    [1, 2, 1, 5],
], dtype=float)
analyze_matrix(A, "A")



矩陣 A：手算範例驗證
矩陣 A (3 x 4):
[[1. 2. 0. 3.]
 [0. 0. 1. 2.]
 [1. 2. 1. 5.]]

rank(A) = 2

A 的 RREF:
[[1. 2. 0. 3.]
 [0. 0. 1. 2.]
 [0. 0. 0. 0.]]
主元欄位 (0-indexed): [0, 2]

行空間基底（取原矩陣主元欄）:
  基底向量 1 = A 的第 1 欄 = [1. 0. 1.]
  基底向量 2 = A 的第 3 欄 = [0. 1. 1.]

零空間基底 (scipy.linalg.null_space):
  基底向量 1 = [ 0.91913472 -0.37134012  0.11763632 -0.05881816]
  基底向量 2 = [-0.09018061 -0.52332707 -0.75788983  0.37894491]
nullity(A) = 2
驗證 A @ (零空間基底) 最大絕對誤差 = 9.58e-16

秩-零度定理: 2 + 2 = 4，欄數 n = 4
驗證通過！rank(A) + nullity(A) = n = 4


## 4. 第二個範例矩陣：再次驗證秩-零度定理

$$
C = \begin{bmatrix} 1 & 2 & 3 \\ 2 & 4 & 6 \\ 1 & 0 & 1 \\ 0 & 1 & 1 \end{bmatrix}
$$

第 2 列 $=2\times$ 第 1 列，第 3 欄 $=$ 第 1 欄 $+$ 第 2 欄，預期秩會小於欄數與列數。


In [6]:
print_section("矩陣 C：第二個範例")
C = np.array([
    [1, 2, 3],
    [2, 4, 6],
    [1, 0, 1],
    [0, 1, 1],
], dtype=float)
analyze_matrix(C, "C")



矩陣 C：第二個範例
矩陣 C (4 x 3):
[[1. 2. 3.]
 [2. 4. 6.]
 [1. 0. 1.]
 [0. 1. 1.]]

rank(C) = 2

C 的 RREF:
[[ 1.  0.  1.]
 [-0.  1.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]
主元欄位 (0-indexed): [0, 1]

行空間基底（取原矩陣主元欄）:
  基底向量 1 = C 的第 1 欄 = [1. 2. 1. 0.]
  基底向量 2 = C 的第 2 欄 = [2. 4. 0. 1.]

零空間基底 (scipy.linalg.null_space):
  基底向量 1 = [-0.57735027 -0.57735027  0.57735027]
nullity(C) = 1
驗證 C @ (零空間基底) 最大絕對誤差 = 8.88e-16

秩-零度定理: 2 + 1 = 3，欄數 n = 3
驗證通過！rank(C) + nullity(C) = n = 3


## 5. 基底與維度：滿秩方陣範例

若矩陣的秩等於欄數，代表所有欄向量線性獨立，本身就構成一組基底，零空間只有 $\{\mathbf{0}\}$。


In [7]:
print_section("矩陣 D：滿秩方陣")
D = np.array([
    [2, 1, 1],
    [1, 3, 2],
    [1, 0, 0],
], dtype=float)
print("D =\n", D)

rank_D = np.linalg.matrix_rank(D)
ns_D = null_space(D)
nullity_D = ns_D.shape[1]
print(f"rank(D) = {rank_D}，nullity(D) = {nullity_D}")
if rank_D == 3:
    print("D 的三個欄向量線性獨立，構成 R^3 的一組基底。")
assert rank_D + nullity_D == D.shape[1]
print(f"秩-零度定理驗證通過：{rank_D} + {nullity_D} = {rank_D + nullity_D} = 3 (欄數)")



矩陣 D：滿秩方陣
D =
 [[2. 1. 1.]
 [1. 3. 2.]
 [1. 0. 0.]]
rank(D) = 3，nullity(D) = 0
D 的三個欄向量線性獨立，構成 R^3 的一組基底。
秩-零度定理驗證通過：3 + 0 = 3 = 3 (欄數)


## 重點整理

- **向量空間**核心是封閉性：加法與純量乘法結果都留在同一集合中。
- **子空間**必須含零向量，且對加法、純量乘法封閉；不過原點的集合都不是子空間。
- **零空間** $\text{Null}(A)=\{\mathbf{x}:A\mathbf{x}=\mathbf{0}\}$：被 $A$ 壓縮成原點的方向。
- **行空間** $\text{Col}(A)$：$A$ 的欄向量張成的空間；$A\mathbf{x}=\mathbf{b}$ 有解 $\iff \mathbf{b}\in\text{Col}(A)$。
- **基底**：線性獨立且生成整個空間的向量集合；**維度**是基底向量個數。
- **秩-零度定理**：$\text{rank}(A)+\text{nullity}(A)=n$（$n$ 為欄數）。
- 求行空間基底要取**原矩陣**中主元欄位對應的欄向量，而不是 RREF 化簡後的欄向量。

## 練習題

1. 判斷 $W=\{(x,y):x+y=0\}$ 是否為 $\mathbb{R}^2$ 的子空間。
   > 提示：檢查零向量與封閉性。答案：是子空間（過原點的直線 $y=-x$）。

2. 判斷 $W=\{(x,y):x\geq 0\}$ 是否為 $\mathbb{R}^2$ 的子空間。
   > 提示：純量乘法 $c=-1$ 時是否仍在集合中？答案：不是子空間。

3. 給定 $B=\begin{bmatrix}1&2\\2&4\end{bmatrix}$，求零空間、行空間基底，驗證秩-零度定理。
   > 答案：rank(B)=1，零空間基底 $\{(-2,1)^T\}$，行空間基底 $\{(1,2)^T\}$，$1+1=2=n$。

4. 給定 $E=\begin{bmatrix}1&0&2\\0&1&3\end{bmatrix}$，求秩、零空間、行空間基底，驗證秩-零度定理。
   > 答案：rank(E)=2，零空間基底 $\{(-2,-3,1)^T\}$，行空間基底 $\{(1,0)^T,(0,1)^T\}$，$2+1=3=n$。

5. 承第 4 題，$\text{Col}(E)$ 是否等於整個 $\mathbb{R}^2$？
   > 答案：是，因為 rank(E)=2=列數，行空間已生成整個 $\mathbb{R}^2$，故 $E\mathbf{x}=\mathbf{b}$ 恆有解。
